# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirátská strana | JIHOČESKÝ KRAJ
email: lukas.kolarik@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
  Web krajského sdružení České pirátské strany v Jihočeském kraji.
keywords: piráti, česká pirátská strana, svoboda, demokracie, jihočeský kraj, české budějovice, JČK
url: "https://jihocesky.pirati.cz" # the base hostname & protocol for your site

administrator:
  email:  jan.suchanek@pirati.cz

emptyArray: []

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-environment-variables

paginate_path: "/aktuality/:num/"
paginate: 15

pagination:
  per_page: 2
  limit: false

exclude:
  - Dockerfile
  - docker-compose.yml
  - deploy_rsa_sandbox.enc
  - deploy_rsa_sandbox.pub
  - navod.md
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /tiskove-zpravy/:title/
collections:
  people:
    output: true
    root: /clenove/
    permalink: /clenove/:path/

  program:
    output: true
    permalink: /:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - foto
        - personContact
        - people
      keywords: členové, příznivci, lidé
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
        - garant
        - program
      keywords: program, volby, 2020, krajské volby, jihočeský kraj

organization:
  name: Pirátská strana | JIHOČESKÝ KRAJ
  shortName: Piráti JČK
  contactUid: lukas.kolarik
  email: lukas.kolarik@pirati.cz
  phone: +420 727 853 151
  address: |
    Jihočeské pirátské centrum
    Na Moráni 3
    120 00 Praha 2

  mapLink: https://goo.gl/maps/AwzVF2nHw3cNnR4L6
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  transparentAccountSpecificSymbol: 110111

contactSummaryItems:
 - type: organizationEmail
 - type: organizationPhone
 - type: organizationRedmineLink
 - type: organizationDataBox
 - type: organizationTransparentAccount
 - type: piratiRootWebsite
   includeMoreLink: true
 - type: custom
   iconClass: fa fa-facebook
   label: Facebook
   body: <a href="https://www.facebook.com/pirati.jck/">@pirati.jck/</a>

calendar:
  # To enable a nicer calendar, make sure you start jekyll with GOOGLE_CALENDAR_APIKEY=[apikey] bundle exec jekyll serve
  title: Nadcházející události
  id: kddvdvu3adcjef2kro4j6mm838@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague

facebook:
  loadSDK: true
  #vyplntě adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: "https://www.facebook.com/pirati.jck/"
  appId: 1526197851008996

instagram:
  profilePage: https://www.instagram.com/pirati.jihocesky/

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

twitter:
  profile: PiratiJcK

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/jihocesky.pirati.cz/edit/gh-pages/
  branch: master


forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/jihocesky.pirati.cz/
  branch: master

github_username:  pirati-web

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { 
      #autoprefixer: {}
    }
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.7.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - assets/img/posts
    - assets/snippet
    - _sass
